apiVersion: apps/v1
kind: Deployment
metadata:
  name: membership-service
  namespace: app # 아까 만든 네임스페이스
spec:
  replicas: 1
  selector:
    matchLabels:
      app: membership-service
  template:
    metadata:
      labels:
        app: membership-service
    spec:
      containers:
        - name: membership-service
          image: membership-service:latest # 우리가 방금 구운 이미지 이름
          imagePullPolicy: Never # 🌟핵심: 도커 허브 가지 말고 Minikube 안에 있는 거 써라!
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: membership-service
  namespace: app
spec:
  selector:
    app: membership-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP